name: Sync to Hugging Face hub
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "wangchonchan@users.noreply.github.com"
          git config --global user.name "Wangchon"
          git push --force https://Wangchon:$HF_TOKEN@huggingface.co/spaces/Wangchon/stock-picking main
